# Generated by Django 4.0.6 on 2022-07-11 13:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.IntegerField()),
                ('phone_number', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('otp_type', models.CharField(choices=[('login', 'LOGIN'), ('signup', 'SIGNUP'), ('forgot_password', 'FORGOT PASSWORD')], max_length=128)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(null=True)),
            ],
        ),
    ]
