# Generated by Django 4.0.6 on 2022-07-12 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
